# SConstruct file for building D/glfw examples
# To use this file, you will need to get 'scons' from http://www.scons.org/
# Once installed, simply type 'scons' to build the programs listed below.
#
# First, however, you will need to perform a couple steps.
# In the ../lib directory, you will need to build the '.lib' files using the provided Makefile.
# That step requires the use of 'implib' which you can download from the DigitalMars site: http://www.digitalmars.com/d
# Once the '.lib' files are created, you may come back to this directory and type 'scons' to build the executables.
# To run the executables, the ../../win32dll/glfw.dll file must be somewhere in your path, or you can copy it to this directory.
#
# $Id: SConstruct,v 1.2 2004-03-26 22:55:09 glennmlewis Exp $

path = ['/dmd/bin', '/dm/bin']
env = Environment(ENV = {'PATH' : path}, DPATH = '-I../imports')

libs = '../lib/glfwdll.lib ../lib/glu32.lib ../lib/opengl32.lib'

env.Program('splitview', Split('splitview.d '+libs))
env.Program('triangle', Split('triangle.d '+libs))
env.Program('gears', Split('gears.d '+libs))
env.Program('particles', Split('particles.d '+libs))
env.Program('boing', Split('boing.d '+libs))
